# Generated by Django 5.2.2 on 2025-06-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("address_street_number", models.IntegerField()),
                ("address_street_name", models.TextField()),
                ("address_apartment_number", models.IntegerField()),
                ("address_zip_code", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                ("date_of_registration", models.DateField()),
                ("party_affiliation", models.TextField()),
                ("precinct_number", models.IntegerField()),
                ("state", models.BooleanField()),
                ("primary", models.BooleanField()),
                ("general", models.BooleanField()),
                ("town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
