# Generated by Django 5.2.2 on 2025-06-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="voter", name="general",),
        migrations.RemoveField(model_name="voter", name="primary",),
        migrations.RemoveField(model_name="voter", name="state",),
        migrations.RemoveField(model_name="voter", name="town",),
        migrations.AddField(
            model_name="voter", name="v20state", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="voter", name="v21primary", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="voter", name="v21town", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="voter", name="v22general", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="voter", name="v23town", field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="address_apartment_number",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="address_street_name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="address_street_number",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="address_zip_code",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="date_of_birth",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="date_of_registration",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter", name="first_name", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter", name="last_name", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="party_affiliation",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voter_score",
            field=models.IntegerField(blank=True),
        ),
    ]
