# Generated by Django 5.2.2 on 2025-06-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_remove_voter_general_remove_voter_primary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="date_of_birth",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="date_of_registration",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.TextField(blank=True),
        ),
    ]
