# Generated by Django 5.2.2 on 2025-06-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0003_alter_voter_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="date_of_birth",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="date_of_registration",
            field=models.DateField(blank=True),
        ),
    ]
