# Generated by Django 5.2.2 on 2025-06-20 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fighter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.TextField(blank=True)),
                ("height", models.IntegerField(blank=True)),
                ("reach", models.IntegerField(blank=True)),
                ("age", models.IntegerField(blank=True)),
                ("nationality", models.TextField(blank=True)),
                ("wins", models.IntegerField(blank=True)),
                ("losses", models.IntegerField(blank=True)),
                ("draws", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeightClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_class", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(blank=True, upload_to="")),
                (
                    "fighter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.fighter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fighter",
            name="weight_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.weightclass"
            ),
        ),
        migrations.CreateModel(
            name="Fight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw", models.BooleanField(blank=True)),
                ("rounds", models.IntegerField(blank=True)),
                ("finish", models.TextField(blank=True)),
                ("date", models.DateField(blank=True)),
                (
                    "loser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loser",
                        to="project.fighter",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner",
                        to="project.fighter",
                    ),
                ),
                (
                    "weight_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.weightclass",
                    ),
                ),
            ],
        ),
    ]
