# Generated by Django 5.2.2 on 2025-06-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fighter", old_name="full_name", new_name="name",
        ),
        migrations.AddField(
            model_name="fighter", name="nickname", field=models.TextField(blank=True),
        ),
    ]
