# Generated by Django 5.2.2 on 2025-06-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_rename_full_name_fighter_name_fighter_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="fight", name="fight_card", field=models.TextField(blank=True),
        ),
    ]
