# Generated by Django 5.2.2 on 2025-06-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_fight_fight_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="fighter",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(blank=True)),
                ("tag", models.TextField(blank=True)),
                (
                    "fight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.fight"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Image",),
    ]
