# Generated by Django 5.2.2 on 2025-06-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_fighter_image_file_rating_delete_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating", old_name="rating", new_name="star_rating",
        ),
        migrations.RemoveField(model_name="fight", name="fight_card",),
    ]
