# Generated by Django 5.2.2 on 2025-06-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_fight_finish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="tag",
            field=models.CharField(
                choices=[
                    ("BB", "Blood Bath"),
                    ("TS", "Technical Showdown"),
                    ("WA", "War of Attrition"),
                ],
                max_length=2,
            ),
        ),
    ]
