# Generated by Django 5.2.2 on 2025-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_alter_rating_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fighter", old_name="image_file", new_name="fight_image",
        ),
        migrations.AddField(
            model_name="fighter",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
