# Generated by Django 5.2.2 on 2025-06-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_rename_image_file_fighter_fight_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="rating", name="tag",),
    ]
