# Generated by Django 5.2.2 on 2025-06-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_remove_rating_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="finish",
            field=models.CharField(
                choices=[
                    ("Decision", "Decision"),
                    ("Unanimous decision", "Unanimousdecision"),
                    ("KO/TKO", "Kotko"),
                    ("Submission", "Submission"),
                ],
                default="Decision",
                max_length=50,
            ),
        ),
    ]
