# Generated by Django 5.2.2 on 2025-06-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_alter_fight_finish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="finish",
            field=models.CharField(
                choices=[
                    ("DECIS", "Decision"),
                    ("UNDEC", "Unanimous decision"),
                    ("KOTKO", "KO/TKO"),
                    ("SUBMI", "Submission"),
                ],
                default="DECIS",
                max_length=5,
            ),
        ),
    ]
