# Generated by Django 5.2.2 on 2025-06-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile_img_url",
            new_name="profile_image_url",
        ),
    ]
