# Generated by Django 5.2.2 on 2025-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0004_alter_statusmessage_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image_url",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
