# Generated by Django 5.2.2 on 2025-06-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0005_alter_profile_profile_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile_image_url",
            new_name="profile_image_file",
        ),
    ]
