# Generated by Django 5.2.2 on 2025-06-06 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0007_image_statusimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mini_fb.profile",
            ),
        ),
    ]
